# Generated by Django 5.0.6 on 2024-06-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
    ]
