# Generated by Django 5.0.6 on 2024-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_slide_button_url_remove_slide_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_title', models.CharField(max_length=50)),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_img', models.ImageField(upload_to='images/')),
                ('pr_price', models.PositiveIntegerField()),
            ],
        ),
    ]
