# Generated by Django 5.0.6 on 2024-06-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_products',
            options={'verbose_name': 'Home product', 'verbose_name_plural': 'Home products'},
        ),
    ]
