# Generated by Django 5.0.6 on 2024-06-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_home_products_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_products',
            name='pr_title',
        ),
    ]
