# Generated by Django 5.0.6 on 2024-06-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about'),
    ]

    operations = [
    ]
