# Generated by Django 5.0.6 on 2024-06-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240621_1742'),
    ]

    operations = [
    ]
