# Generated by Django 5.0.6 on 2024-06-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240621_1842'),
    ]

    operations = [
    ]
