# Generated by Django 5.0.6 on 2024-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20240621_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60, verbose_name='Contact first name')),
                ('lname', models.CharField(max_length=60, verbose_name='Contact last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('message', models.TextField(verbose_name='Contact text')),
            ],
        ),
    ]
