# Generated by Django 5.0.6 on 2024-06-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
